* 将nginx更换为tengine，并使用lua来管理节点的配置文件

diff --git a/amengcdn b/amengcdn
--- a/amengcdn
+++ b/amengcdn
@@ -1,23 +1,23 @@
 #!/bin/bash
 
-#description: opencdn
+#description: amengcdn
 #chkconfig: 2345 20 81
 
-EXEC="opencdn"
+EXEC="amengcdn"
 EXEC_INFO="send_info"
 PID_FILE="/var/run/$EXEC.pid"
-OPENCDN_LOG_PATH="/var/log/opencdn"
-OPENCDN_EXEC_PATH="/usr/local/opencdn/sbin"
-OPENCDN_CONF_FILE="/usr/local/opencdn/conf/opencdn.conf"
+AMENGCDN_LOG_PATH="/home/data1/amengcdn/logs"
+AMENGCDN_EXEC_PATH="/usr/local/amengcdn/sbin"
+AMENGCDN_CONF_FILE="/usr/local/amengcdn/conf/amengcdn.conf"
 
 . /etc/rc.d/init.d/functions
 
-[ -x ${OPENCDN_EXEC_PATH}/$EXEC_INFO ] || echo "ERROR: $EXEC_INFO not found"
+[ -x ${AMENGCDN_EXEC_PATH}/$EXEC_INFO ] || echo "ERROR: $EXEC_INFO not found"
 [ -f "$PID_FILE" ] || touch $PID_FILE
 
 function change_console_ip()
 {
-	new_console_ip=`cat ${OPENCDN_CONF_FILE} | grep "Console_IP" | awk -F = '{print $2}'`
+	new_console_ip=`cat ${AMENGCDN_CONF_FILE} | grep "Console_IP" | awk -F = '{print $2}'`
 	[ ! -z "${new_console_ip}" ] || return 1
 
 	#change console IP of rsync
@@ -59,7 +59,7 @@ start()
 		/usr/bin/rsync --daemon 
 		service syslog-ng start
 
-		nohup /bin/bash ${OPENCDN_EXEC_PATH}/send_info >> ${OPENCDN_LOG_PATH}/send_info.log 2>&1 &
+		nohup /bin/bash ${AMENGCDN_EXEC_PATH}/send_info >> ${AMENGCDN_LOG_PATH}/send_info.log 2>&1 &
 		echo "running" > $PID_FILE
 		usleep 100
 		echo "Starting $EXEC: [  OK  ]"        
diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,7 +1,7 @@
 #!/bin/bash
 
-# Hello boys and girls, Welcome to OpenCDN!
-# OpenCDN a open-source management platform, which can help you build node-hosts in 5 minutes.
+# Hello boys and girls, Welcome to AmengCDN!
+# AmengCDN a open-source management platform, which can help you build node-hosts in 5 minutes.
 # The system consists of the Control Center(CC) and Node Host(NH). The CC can monitor a basic 
 # system information on each node, such as cpu usage and health status. CC also can collect logs 
 # of nginx from all node-hosts. You'd better reference to source code
@@ -32,14 +32,29 @@ function file_noexists_download()
 
 function killd_server()
 {
+    service amengcdn stop
+
 	kill -9 `ps aux | grep "httpd" | awk "{print $2}"` > /dev/null 2>&1 
-	kill -9 `ps aux | grep "mysqld" | awk "{print $2}"`  > /dev/null 2>&1 
+	kill -9 `ps aux | grep "mysqld" | awk "{print $2}"`  > /dev/null 2>&1
+
 	rm -rf /etc/localtime
 	ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
 
 	yum install -y ntp
 	ntpdate -u pool.ntp.org
 	date
+
+	rpm -e nginx
+
+	rm -f /etc/init.d/amengcdn
+	rm -f /etc/init.d/nginx
+	rm -f /var/run/nginx.pid
+	rm -rf /usr/local/nginx
+	rm -rf /usr/local/amengcdn
+	rm -rf /home/data1/amengcdn/
+
+	chkconfig --del amengcdn
+	chkconfig --del nginx
 
 	rpm -qa|grep  httpd
 	rpm -e httpd
@@ -83,10 +98,10 @@ function get_system_basic_info()
 	echo "Press any key to start install AmengCDN , please wait ......"
 	char=`get_char`
 
-	OpenCDN_Manage_IP=""
+	AmengCDN_Manage_IP=""
 	echo ""
 	echo -n "Now input IP of CDN Management : "
-	read OpenCDN_Manage_IP
+	read AmengCDN_Manage_IP
 
 	IS_64=`uname -a | grep "x86_64"`
 	if [ -z "${IS_64}" ]
@@ -114,18 +129,18 @@ get_system_basic_info
 
 killd_server
 
-OPENCDN_LOG_PATH="/var/log/opencdn"
-OPENCDN_EXEC_PATH="/usr/local/opencdn/sbin"
-OPENCDN_CONF_PATH="/usr/local/opencdn/conf"
-OPENCDN_PIPE_PATH="/usr/local/opencdn/pipe"
-OPENCDN_CONF_FILE="/usr/local/opencdn/conf/opencdn.conf"
+AMENGCDN_LOG_PATH="/home/data1/amengcdn/logs/"
+AMENGCDN_EXEC_PATH="/usr/local/amengcdn/sbin"
+AMENGCDN_CONF_PATH="/usr/local/amengcdn/conf"
+AMENGCDN_PIPE_PATH="/home/data1/amengcdn/pipe"
+AMENGCDN_CONF_FILE="/usr/local/amengcdn/conf/amengcdn.conf"
 
-mkdir -p ${OPENCDN_LOG_PATH}
-mkdir -p ${OPENCDN_EXEC_PATH}
-mkdir -p ${OPENCDN_CONF_PATH}
-mkdir -p ${OPENCDN_PIPE_PATH}
+mkdir -p ${AMENGCDN_LOG_PATH}
+mkdir -p ${AMENGCDN_EXEC_PATH}
+mkdir -p ${AMENGCDN_CONF_PATH}
+mkdir -p ${AMENGCDN_PIPE_PATH}
 
-access_log="${OPENCDN_PIPE_PATH}/access.pipe"
+access_log="${AMENGCDN_PIPE_PATH}/access.pipe"
 rm -f $access_log
 mkfifo ${access_log}
 if [ ! -p "${access_log}" ] 
@@ -134,7 +149,7 @@ then
 	exit 1;
 fi
 
-sys_fifo="${OPENCDN_PIPE_PATH}/sys_info.pipe"
+sys_fifo="${AMENGCDN_PIPE_PATH}/sys_info.pipe"
 rm -f $sys_fifo
 mkfifo $sys_fifo
 if [ ! -p "${sys_fifo}" ] 
@@ -145,40 +160,47 @@ fi
 
 
 OLD_DIR=`pwd`
-mv ${OLD_DIR}/opencdn.conf ${OPENCDN_CONF_PATH}
+mv ${OLD_DIR}/amengcdn.conf ${AMENGCDN_CONF_PATH}
 
-sed -i "s/localhost/$OpenCDN_Manage_IP/g" ${OPENCDN_CONF_PATH}/opencdn.conf
+sed -i "s/localhost/$AmengCDN_Manage_IP/g" ${AMENGCDN_CONF_PATH}/amengcdn.conf
 
 echo "===========================nginx install start===================================="
-sed -i 's/^exclude/#exclude/'  /etc/yum.conf && yum -y install gcc && sed -i 's/^#exclude/exclude/'  /etc/yum.conf
+pushd Tengine
+chmod u+x ./tengine.sh
+./tengine.sh
+popd
+echo "===========================nginx install completed================================"
 
-yum -y install gcc gcc-c++ autoconf automake make
-yum -y install zlib zlib-devel openssl openssl--devel pcre pcre-devel
-yum -y install bc
+#echo "===========================nginx install start===================================="
+#sed -i 's/^exclude/#exclude/'  /etc/yum.conf && yum -y install gcc && sed -i 's/^#exclude/exclude/'  /etc/yum.conf
 
-mv  ${OLD_DIR}/nginx.txt /tmp/
-mv -f  ${OLD_DIR}/conf /tmp/ 
-cd /tmp
+#yum -y install gcc gcc-c++ autoconf automake make
+#yum -y install zlib zlib-devel openssl openssl--devel pcre pcre-devel
+#yum -y install bc
 
-wget http://nginx.org/download/nginx-1.2.0.tar.gz
-if [ $? -eq 0 ]
-then
-	tar -zxvf nginx-1.2.0.tar.gz
-	rm -f nginx-1.2.0.tar.gz
-else
-	echo "Downloading http://nginx.org/download/nginx-1.2.0.tar.gz failured !!!"
-	exit 1
-fi 
+#mv  ${OLD_DIR}/nginx.txt /tmp/
+#mv -f  ${OLD_DIR}/conf /tmp/
+#cd /tmp
 
-wget http://labs.frickle.com/files/ngx_cache_purge-1.6.tar.gz
-if [ $? -eq 0 ]
-then
-	tar -zxvf ngx_cache_purge-1.6.tar.gz
-	rm -f ngx_cache_purge-1.6.tar.gz
-else
-	echo "Downloading http://labs.frickle.com/files/ngx_cache_purge-1.3.tar.gz failured !!!"
-	exit 1
-fi 
+#wget http://nginx.org/download/nginx-1.2.0.tar.gz
+#if [ $? -eq 0 ]
+#then
+#	tar -zxvf nginx-1.2.0.tar.gz
+#	rm -f nginx-1.2.0.tar.gz
+#else
+#	echo "Downloading http://nginx.org/download/nginx-1.2.0.tar.gz failured !!!"
+#	exit 1
+#fi
+
+#wget http://labs.frickle.com/files/ngx_cache_purge-1.6.tar.gz
+#if [ $? -eq 0 ]
+#then
+#	tar -zxvf ngx_cache_purge-1.6.tar.gz
+#	rm -f ngx_cache_purge-1.6.tar.gz
+#else
+#	echo "Downloading http://labs.frickle.com/files/ngx_cache_purge-1.3.tar.gz failured !!!"
+#	exit 1
+#fi
 
 #file_noexists_download ./pcre-8.33.tar.gz http://ftp.cs.stanford.edu/pub/exim/pcre/pcre-8.33.tar.gz
 #file_noexists_download ./openssl-1.0.1e.tar.gz http://www.openssl.org/source/openssl-1.0.1e.tar.gz
@@ -186,137 +208,137 @@ fi
 #file_noexists_download ./gperftools-2.0.tar.gz http://pkgs.fedoraproject.org/repo/pkgs/gperftools/gperftools-2.0.tar.gz/13f6e8961bc6a26749783137995786b6/gperftools-2.0.tar.gz
 
 
-wget http://ftp.cs.stanford.edu/pub/exim/pcre/pcre-8.10.tar.gz
-if [ $? -eq 0 ]
-then
-	tar -zxvf pcre-8.10.tar.gz
-	rm -f pcre-8.10.tar.gz
-else
-	echo "Downloading http://ftp.cs.stanford.edu/pub/exim/pcre/pcre-8.10.tar.gz failured !!!"
-	exit 1
-fi
+#wget http://ftp.cs.stanford.edu/pub/exim/pcre/pcre-8.10.tar.gz
+#if [ $? -eq 0 ]
+#then
+#	tar -zxvf pcre-8.10.tar.gz
+#	rm -f pcre-8.10.tar.gz
+#else
+#	echo "Downloading http://ftp.cs.stanford.edu/pub/exim/pcre/pcre-8.10.tar.gz failured !!!"
+#	exit 1
+#fi
 
-wget http://www.openssl.org/source/openssl-1.0.1e.tar.gz
-if [ $? -eq 0 ]
-then
-	tar -zxvf openssl-1.0.1e.tar.gz
-	rm -f openssl-1.0.1e.tar.gz
-else
-	echo "Downloading http://www.openssl.org/source/openssl-1.0.1e.tar.gz failured !!!"
-	exit 1
-fi
+#wget http://www.openssl.org/source/openssl-1.0.1e.tar.gz
+#if [ $? -eq 0 ]
+#then
+#	tar -zxvf openssl-1.0.1e.tar.gz
+#	rm -f openssl-1.0.1e.tar.gz
+#else
+#	echo "Downloading http://www.openssl.org/source/openssl-1.0.1e.tar.gz failured !!!"
+#	exit 1
+#fi
 
-if [ "${CPU_ARC}" == "x86_64" ]
-then
-	wget http://ftp.twaren.net/Unix/NonGNU/libunwind/libunwind-0.99-alpha.tar.gz
-	tar zxvf libunwind-0.99-alpha.tar.gz
-	cd libunwind-0.99-alpha/
-	CFLAGS=-fPIC ./configure
-	make CFLAGS=-fPIC
-	make CFLAGS=-fPIC install
-fi
+#if [ "${CPU_ARC}" == "x86_64" ]
+#then
+#	wget http://ftp.twaren.net/Unix/NonGNU/libunwind/libunwind-0.99-alpha.tar.gz
+#	tar zxvf libunwind-0.99-alpha.tar.gz
+#	cd libunwind-0.99-alpha/
+#	CFLAGS=-fPIC ./configure
+#	make CFLAGS=-fPIC
+#	make CFLAGS=-fPIC install
+#fi
 
-wget http://pkgs.fedoraproject.org/repo/pkgs/gperftools/gperftools-2.0.tar.gz/13f6e8961bc6a26749783137995786b6/gperftools-2.0.tar.gz
-if [ $? -eq 0 ]
-then
-	tar -zxvf gperftools-2.0.tar.gz
-	rm -f gperftools-2.0.tar.gz
-else
-	echo "http://pkgs.fedoraproject.org/repo/pkgs/gperftools/gperftools-2.0.tar.gz/13f6e8961bc6a26749783137995786b6/gperftools-2.0.tar.gz failured !!!"
-	exit 1
-fi 
+#wget http://pkgs.fedoraproject.org/repo/pkgs/gperftools/gperftools-2.0.tar.gz/13f6e8961bc6a26749783137995786b6/gperftools-2.0.tar.gz
+#if [ $? -eq 0 ]
+#then
+#	tar -zxvf gperftools-2.0.tar.gz
+#	rm -f gperftools-2.0.tar.gz
+#else
+#	echo "http://pkgs.fedoraproject.org/repo/pkgs/gperftools/gperftools-2.0.tar.gz/13f6e8961bc6a26749783137995786b6/gperftools-2.0.tar.gz failured !!!"
+#	exit 1
+#fi
 
-pushd gperftools-2.0
-./configure --prefix=/usr
-make&&make install
-popd
+#pushd gperftools-2.0
+#./configure --prefix=/usr
+#make&&make install
+#popd
 
-echo "/usr/local/lib" > /etc/ld.so.conf.d/usr_local_lib.conf
-/sbin/ldconfig
+#echo "/usr/local/lib" > /etc/ld.so.conf.d/usr_local_lib.conf
+#/sbin/ldconfig
 
-mkdir /tmp/tcmalloc
-chmod 0777 /tmp/tcmalloc
+#mkdir /tmp/tcmalloc
+#chmod 0777 /tmp/tcmalloc
 
-mkdir /usr/local/nginx
-cd /usr/local/nginx
+#mkdir /usr/local/nginx
+#cd /usr/local/nginx
 
 ## change file before compile
-sed -i 's/\"nginx/\"OpenCDN Beta/i' /tmp/nginx-1.2.0/src/core/nginx.hi
-sed 's/>nginx</>OpenCDN Beta</' -i /tmp/nginx-1.2.0/src/http/ngx_http_special_response.c
-sed -i 's/\" NGINX_VER \"/OpenCDN beta/' /tmp/ngx_cache_purge-1.6/ngx_cache_purge_module.c
+#sed -i 's/\"nginx/\"AmengCDN Beta/i' /tmp/nginx-1.2.0/src/core/nginx.hi
+#sed 's/>nginx</>AmengCDN Beta</' -i /tmp/nginx-1.2.0/src/http/ngx_http_special_response.c
+#sed -i 's/\" NGINX_VER \"/AmengCDN beta/' /tmp/ngx_cache_purge-1.6/ngx_cache_purge_module.c
 
 ## complie nginx with new args
-groupadd www
-useradd -g www -s /bin/false -M www
+#groupadd www
+#useradd -g www -s /bin/false -M www
 
-pushd /tmp/nginx-1.2.0
-./configure --user=www --group=www --prefix=/usr/local/nginx --with-pcre=../pcre-8.10 --with-openssl=../openssl-1.0.1e  --add-module=../ngx_cache_purge-1.6 --with-http_stub_status_module --with-http_ssl_module --with-http_gzip_static_module --without-mail_pop3_module     --without-mail_smtp_module     --without-mail_imap_module     --without-http_uwsgi_module     --without-http_scgi_module --with-google_perftools_module
-make && make install
-if [ $? -ne 0 ];then
-	echo "error"
-	exit 1
-fi 
-popd
+#pushd /tmp/nginx-1.2.0
+#./configure --user=www --group=www --prefix=/usr/local/nginx --with-pcre=../pcre-8.10 --with-openssl=../openssl-1.0.1e  --add-module=../ngx_cache_purge-1.6 --with-http_stub_status_module --with-http_ssl_module --with-http_gzip_static_module --without-mail_pop3_module     --without-mail_smtp_module     --without-mail_imap_module     --without-http_uwsgi_module     --without-http_scgi_module --with-google_perftools_module
+#make && make install
+#if [ $? -ne 0 ];then
+#	echo "error"
+#	exit 1
+#fi
+#popd
 
 #set auto start scripts
-mv /tmp/nginx.txt /etc/init.d/nginx
+#mv /tmp/nginx.txt /etc/init.d/nginx
 
-chmod u+x /etc/init.d/nginx
+#chmod u+x /etc/init.d/nginx
 
-rm -rf /usr/local/nginx/conf
-mv -f /tmp/conf /usr/local/nginx/
+#rm -rf /usr/local/nginx/conf
+#mv -f /tmp/conf /usr/local/nginx/
 
-chkconfig --add nginx
-chkconfig --level 345 nginx on
-chkconfig --list nginx
+#chkconfig --add nginx
+#chkconfig --level 345 nginx on
+#chkconfig --list nginx
 
 #service nginx start
 ## Create cache and temp
-mkdir /home/cache/
+#mkdir /home/cache/
 #mkdir /home/logs/
-mkdir /home/temp/
+#mkdir /home/temp/
 
 
 ## Set the provilige of cache
-chown www.www -R /home/cache /home/temp
-chmod -R 777 /home/cache /home/temp
+#chown www.www -R /home/cache /home/temp
+#chmod -R 777 /home/cache /home/temp
 
-echo "===========================nginx install completed===================================="
+#echo "===========================nginx install completed===================================="
 
-echo "===========================rsync install start========================================"
+#echo "===========================rsync install start========================================"
 
-yum -y remove rsync 
-yum -y install rsync 
+#yum -y remove rsync
+#yum -y install rsync
 
-cd ${OLD_DIR}
+#cd ${OLD_DIR}
 
-if [ ! -f "./inotify-tools-3.14.tar.gz" ]
-then
-	wget http://pkgs.fedoraproject.org/repo/pkgs/inotify-tools/inotify-tools-3.14.tar.gz/b43d95a0fa8c45f8bab3aec9672cf30c/inotify-tools-3.14.tar.gz
-fi
+#if [ ! -f "./inotify-tools-3.14.tar.gz" ]
+#then
+#	wget http://pkgs.fedoraproject.org/repo/pkgs/inotify-tools/inotify-tools-3.14.tar.gz/b43d95a0fa8c45f8bab3aec9672cf30c/inotify-tools-3.14.tar.gz
+#fi
 
-tar zxvf inotify-tools-3.14.tar.gz
-rm -rf inotify-tools-3.14.tar.gz
-pushd inotify-tools-3.14
-./configure && make && make install
-popd
+#tar zxvf inotify-tools-3.14.tar.gz
+#rm -rf inotify-tools-3.14.tar.gz
+#pushd inotify-tools-3.14
+#./configure && make && make install
+#popd
 
-ln -sv /usr/local/lib/libinotify* /usr/lib/
-ln -s /usr/local/lib/libinotifytools.so.0 /usr/lib64/libinotifytools.so.0
+#ln -sv /usr/local/lib/libinotify* /usr/lib/
+#ln -s /usr/local/lib/libinotifytools.so.0 /usr/lib64/libinotifytools.so.0
 
-echo "ocdn:ocdn.me" >/etc/rsyncd.pwd
-chmod 600 /etc/rsyncd.pwd
+#echo "ocdn:ocdn.me" >/etc/rsyncd.pwd
+#chmod 600 /etc/rsyncd.pwd
 
-USER=ocdn
-PASSWD=ocdn.me
-cd ${OLD_DIR}
+#USER=ocdn
+#PASSWD=ocdn.me
+#cd ${OLD_DIR}
 
-mv -f ${OLD_DIR}/rsyncd.conf  /etc/rsyncd.conf
-sed "s/0\.0\.0\.0/$OpenCDN_Manage_IP/g" -i /etc/rsyncd.conf
+#mv -f ${OLD_DIR}/rsyncd.conf  /etc/rsyncd.conf
+#sed "s/0\.0\.0\.0/$AmengCDN_Manage_IP/g" -i /etc/rsyncd.conf
 
 #echo "/usr/bin/rsync --daemon" >> /etc/rc.d/rc.local
 
-echo "===========================rsync install completed===================================="
+#echo "===========================rsync install completed===================================="
 
 mv /etc/init.d/iptables /etc/init.d/iptables.bak
 rm -f /etc/sysconfig/iptables
@@ -329,11 +351,11 @@ service iptables restart
 mv -f ${OLD_DIR}/nginxmon  /usr/local/nginx/sbin/ -f
 
 chmod u+x /usr/local/nginx/sbin/nginxmon 
-echo "nohup /bin/bash /usr/local/nginx/sbin/nginxmon > ${OPENCDN_LOG_PATH}/nginxmon.log 2>&1 &" >> /etc/rc.d/rc.local
-nohup /bin/bash /usr/local/nginx/sbin/nginxmon &> ${OPENCDN_LOG_PATH}/nginxmon.log 2>&1 &
+echo "nohup /bin/bash /usr/local/nginx/sbin/nginxmon > ${AMENGCDN_LOG_PATH}/nginxmon.log 2>&1 &" >> /etc/rc.d/rc.local
+nohup /bin/bash /usr/local/nginx/sbin/nginxmon &> ${AMENGCDN_LOG_PATH}/nginxmon.log 2>&1 &
 
-mv -f ${OLD_DIR}/send_info ${OPENCDN_EXEC_PATH}
-chmod u+x ${OPENCDN_EXEC_PATH}/send_info
+mv -f ${OLD_DIR}/send_info ${AMENGCDN_EXEC_PATH}
+chmod u+x ${AMENGCDN_EXEC_PATH}/send_info
 
 echo "===========================syslog install start===================================="
 
@@ -343,7 +365,7 @@ yum -y install syslog-ng
 cd ${OLD_DIR}
 mv /etc/syslog-ng/syslog-ng.conf /etc/syslog-ng/syslog-ng.conf.bak
  
-sed -i "s/0\.0\.0\.0/$OpenCDN_Manage_IP/g" syslog-ng.conf
+sed -i "s/0\.0\.0\.0/$AmengCDN_Manage_IP/g" syslog-ng.conf
 mv -f ${OLD_DIR}/syslog-ng.conf /etc/syslog-ng/syslog-ng.conf
 chkconfig syslog-ng on
 service syslog-ng start > /dev/null 2>&1
@@ -351,17 +373,17 @@ service nginx start
 
 echo "===========================syslog install completed===================================="
 
-chmod 777 ${OLD_DIR}/opencdn
-mv -f ${OLD_DIR}/opencdn /etc/init.d/
-chkconfig --add opencdn
-service opencdn restart 
+chmod 777 ${OLD_DIR}/amengcdn
+mv -f ${OLD_DIR}/amengcdn /etc/init.d/
+chkconfig --add amengcdn
+service amengcdn restart
 
-echo "==========================OpenCDN===================================="
+echo "==========================AmengCDN===================================="
 echo "*                                                                   *"
-echo "*service opencdn [start|stop|restart|status]                        *"
-echo "*sys_info log path : /var/log/opencdn/send_info.log                 *"
+echo "*service amengcdn [start|stop|restart|status]                        *"
+echo "*sys_info log path : /home/data1/amengcdn/logs/send_info.log                 *"
 echo "*                                                                   *"
-echo "==========================OpenCDN===================================="
+echo "==========================AmengCDN===================================="
 
 ## Clean source file
 cd /tmp
